---
title: 10.4.4 Java 7增强的throw语句
categories: 
  - 疯狂Java讲义 (第4版)
  - 第10章 异常处理
  - 10.4 使用throw抛出异常
date: 2019-07-13 22:12:31
updated: 2019-11-25 11:30:03
abbrlink: b58aec7e
---
<div id='my_toc'>

- [10.4.4 Java 7增强的throw语句](/JavaReadingNotes/b58aec7e/#10-4-4-Java-7增强的throw语句)
    - [总结](/JavaReadingNotes/b58aec7e/#总结)

</div>
<!--more-->
<script>if (navigator.platform.toLowerCase() == 'win32'){document.getElementById('my_toc').style.display = 'none';}</script>

<!--end-->
# 10.4.4 Java 7增强的throw语句 #
对于如下代码:
```java
try
{
	new FileOutputStream("a.txt");
}
catch (Exception ex)
{
	ex.printStackTrace();
	throw ex;        // ①
}
```
上面代码片段中的①号代码再次抛出了捕获到的异常,但这个ex对象的情况比较特殊:程序捕获该异常时,声明该异常的类型为`Exception`;但实际上`try`块中只调用了`FileOutputStream`构造器,这个构造器声明只是抛出了`FileNotFoundException`异常。
在`Java 7`以前,`Java`编译器的处理"简单而粗暴"——由于在捕获该异常时声明`ex`的类型是`Exception`,因此`Java`编译器认为这段代码可能抛出`Exception`异常,所以`包含这段代码的方法`通常需要声明抛出`Exception`异常。例如如下`main`方法。
```java
import java.io.*;

public class ThrowTest2
{
	public static void main(String[] args)
		// Java 6认为①号代码可能抛出Exception，
		// 所以此处声明抛出Exception
		throws Exception
	{
		try
		{
			new FileOutputStream("a.txt");
		}
		catch (Exception ex)
		{
			ex.printStackTrace();
			throw ex;        // ①
		}
	}
}
```
从`Java 7`开始,`Java`编译器会执行更细致的检查,**`Java`编译器会检查`throw`语句抛出异常的实际类型**,这样编译器知道①号代码处实际上只可能抛出`FileNotFoundException`异常,因此在调用者`main`方法签名中只要声明抛出`FileNotFound Exception`异常即可。即可以将代码改为如下形式:
```java
import java.io.*;

public class ThrowTest2
{
	public static void main(String[] args)
		// Java 7会检查①号代码可能抛出异常的实际类型，
		// 因此此处只需声明抛出FileNotFoundException即可。
		throws FileNotFoundException
	{
		try
		{
			new FileOutputStream("a.txt");
		}
		catch (Exception ex)
		{
			ex.printStackTrace();
			throw ex;        // ①
		}
	}
}
```
## 总结 ##
从`Java 7`开始,**`Java`编译器会检查`throw`语句抛出异常的实际类型**,而直接使用`catch`块声明的参数的类型。

